plugins {
    id "com.android.application"
}

android {
    namespace "com.alexcodesthings.ronface"
    compileSdk 35

    defaultConfig {
        applicationId "com.alexcodesthings.ronface"
        minSdk 22
        targetSdk 35
        versionCode 17
        versionName "0.1.16"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}
